version: '3.8'

services:

  sample:
    container_name: Clairvoyance
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]
    stdin_open: true
    tty: true