version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        requirements: requirements/requirements_dev.txt
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=clairvoyance.settings.settings_dev
    volumes:
      - ./backend:/app/backend
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    container_name: Clairvoyance_FE
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: ['npm', 'start']
    stdin_open: true
    tty: true
