# Generated by Django 3.0.7 on 2020-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20200811_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
