# Generated by Django 3.0.7 on 2020-08-14 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 16, 25, 17, 380560)),
        ),
    ]
