# Generated by Django 3.0.7 on 2020-08-14 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_auto_20200814_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
