# Generated by Django 3.0.7 on 2020-06-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='user',
            new_name='user_id',
        ),
    ]
