# Generated by Django 3.0.7 on 2020-06-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200630_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='user_id',
            new_name='user',
        ),
    ]
