# Generated by Django 3.0.7 on 2020-07-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goalupdate'),
        ('habits', '0004_habitupdate'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitupdate',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='habitupdate',
            name='post',
        ),
        migrations.RemoveField(
            model_name='habitupdate',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='goal_updates',
            field=models.ManyToManyField(to='goals.GoalUpdate'),
        ),
        migrations.AddField(
            model_name='post',
            name='habit_updates',
            field=models.ManyToManyField(to='habits.HabitUpdate'),
        ),
        migrations.DeleteModel(
            name='GoalUpdate',
        ),
        migrations.DeleteModel(
            name='HabitUpdate',
        ),
    ]
