# Generated by Django 3.0.7 on 2020-07-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habitupdate'),
        ('posts', '0002_auto_20200707_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='habit_updates',
            field=models.ManyToManyField(blank=True, to='habits.HabitUpdate'),
        ),
    ]
