# Generated by Django 3.0.7 on 2020-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goalupdate'),
        ('posts', '0004_auto_20200810_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='future_tasks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='goal_updates',
            field=models.ManyToManyField(blank=True, to='goals.GoalUpdate'),
        ),
    ]
